package edu.web.news.controller.command;

public enum CommandName {

	DO_AUTH, DO_REGISTRATION, CHANGE_LOCALE, LOGOUT, FIND_USER_BY_EMAIL, ASSIGN_ROLE,

	GO_TO_START_PAGE, GO_TO_AUTHENTICATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_ADMIN_PAGE, GO_TO_EDIT_PAGE, GO_TO_ASSIGN_ROLE_PAGE,
	
	ADD_NEWS, DELETE_NEWS, EDIT_NEWS, VIEW_NEWS, GET_NEWS_BY_CATEGORY,

	NO_SUCH_COMMAND
}
